import type { Metadata } from "next";
import { Inter, Noto_Sans, Raleway } from "next/font/google";
import "./globals.css";

const fontInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const fontNoto = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

const fontRaleway = Raleway({
  variable: "--font-raleway-family",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontInter.variable} ${fontNoto.variable} ${fontRaleway.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
